### ISSUE TITLE
Include the class and line that database operations came from

### ISSUE THREAD

**Issue by babula** [financialforcedev/debug-log-analyzer#11]
### Is your feature request related to a problem?
While it's really nice to see the DML and SOQL statements grouped so that we can see things like what actions are repeating or which are not selective enough, we then need to go find where that specific statement is. It would be great if the relevant class and line could be included in the results table so we can quickly navigate to them.

### Describe the solution you'd like
Add stack trace information to the results tables in the Database tab. DML statements are not grouped by the specific statement so they may need an expandable section for each so you can see the different lines that, for example, updated a case.

### Additional context
Unrelated, but I would also recommend removing the 'x' from the count and rows. It becomes distracting and doesn't offer any additional beneficial information. I'd rather just see the number by itself as it's easier to comprehend at a quick glance.

Edit: One more suggestion for the Database tab is to have an option to split out everything by namespace. As an ISV, I'm often looking specifically at our namespace(s) to determine if/where an issue is occurring.

**Comment by kjonesffdc** [comment]
Thanks for the idea. Makes perfect sense that you would want to be able to do this. As we are about to go into holiday season it might be a few weeks before we can take a look at implementing.
