### ISSUE TITLE
feat: Implement Breadcrumbs

### ISSUE THREAD

**Issue by sjonwilson** [financialforcedev/debug-log-analyzer#142]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

To display a list of markers across the top of the call tree, one for each parent node.
Each marker to be small (just display its type) and have a tooltip to display the line text.
These markers should be updated whenever a node is clicked in the tree and the tree-node highlighted to show which line the breadcrumbs relate to.

### Describe alternatives you've considered

I previously experimented with a navigate to parent action on click, but I didn't want to navigate - I just wanted context.

### Additional context

A nodes parents can be hard to see in a large tree due to scrolling. This makes it easier to find out where we are.

**Comment by lcotterffdc** [comment]
Re opening as this does not work too well in dark mode in vscode. The text is white..
