### ISSUE TITLE
allow to load log from file

### ISSUE THREAD

**Issue by chasd00** [financialforcedev/debug-log-analyzer#15]
It would be awesome to be able to load a log from the local file system for analysis. Sometimes i get logs emailed to me from orgs that i don't have access to. Or a developer asks me about a specific log they have locally and it would take a while to find it in the org.

**Comment by smaddox-sf** [comment]
HI @chasd00 - You can drag & drop a local file onto VS Code and it will open in the default log viewer.  From there, right-click and choose `Log: Show Log for Analysis` command to open the Log Analyzer.

**Comment by lukecotter** [comment]
The `Log: Show Log for Analysis` command also exists in the command palette when you have a log open.
