### ISSUE TITLE
feat: More Distinct Timeline Colors

### ISSUE THREAD

**Issue by robertStrunk** [financialforcedev/debug-log-analyzer#196]
### Is your feature request related to a problem?
User Experience Related

This is an amazing tool, thank you for working on it! I sometimes have a hard time distinguishing between the colors in the timeline. My eyes have trouble distinguishing between the "SOQL", "Method", and "Flow" blocks. It is also difficult for me to distinguish between the "DML" and "Workflow" blocks. If other people are also affected by this I think it might be a good idea to change the colors so they aren't so close. 
Please see the below image for what I am referring to. 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/47643610/204868109-080fdfa3-6332-4707-8cd0-a3053a6b6f91.png">

**Comment by lcotterffdc** [comment]
You are absolutely right the colours can be hard to tell apart. We will definitely look at making the differentiation easier.

In the mean time you can check out the [color settings](https://github.com/financialforcedev/debug-log-analyzer#color-settings) section in the readme to pick your own custom ones.

**Comment by robertStrunk** [comment]
@lcotterffdc I had no idea those color settings existed or I would not have raised this issue. Thank you!

**Comment by lcotterffdc** [comment]
@robertStrunk 
I have raised a [pull request](https://github.com/financialforcedev/debug-log-analyzer/pull/230) to try and make the colours easier to tell apart.
I would to see what you think and if this would help people out of the box.
https://github.com/financialforcedev/debug-log-analyzer/pull/230
