### ISSUE TITLE
Publish the extension on the VSX Registry

### ISSUE THREAD

**Issue by AllanOricil** [financialforcedev/debug-log-analyzer#23]
### Is your feature request related to a problem?
No, I just noticed yesterday that my extension is the only one in the VSX Registry (https://open-vsx.org/)  and the only one available to be used in Gitpod.  

Allows for use on Gitpod and anything else using the Open VSX Registry

![image](https://user-images.githubusercontent.com/55927613/114029466-7107e000-9871-11eb-9b26-c8cc5887b811.png)

This is the guide to publish your extension there: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

### Describe the solution you'd like
Publish the extension to VSX Registry.

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by AllanOricil** [comment]
nice job

**Comment by lukecotter** [comment]
> nice job @lukecotter 

@AllanOricil 
No problem. Keep an eye out for the next release 👍
