### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined.

### ISSUE THREAD

**Issue by jclark-dot-org** [financialforcedev/debug-log-analyzer#3]
### Summary

When trying to view a log loaded directly from a file, using the command palette command, "Log: Show Log Analysis", I receive the error "TypeError: Cannot read property 'path' of undefined."

### Steps To Reproduce:

1.  Download a log from Salesforce.  Developer Console, Logs, right-click a log, choose Download
1.  Open the log in VSCode.
1.  Attempt to view the Log Analyzer:  CMD+P, Log: Show Log Analysis

### Expected result

Log is displayed

 in Log Analyzer

### Actual result

An error popup occurs, "TypeError: Cannot read property 'path' of undefined."

### Additional information

![Screen Shot 2020-12-10 at 2 52 27 PM](https://user-images.githubusercontent.com/2294694/101822626-99681380-3af7-11eb-8ae9-46dbee385e88.png)

I've attached a frivolous anonymous apex log that exhibits the issue (I needed something without client info), but this happens with every log I have attempted.

[apex-07L2F00000IJrxkUAD.log](https://github.com/financialforcedev/debug-log-analyzer/files/5675305/apex-07L2F00000IJrxkUAD.log)

**VS Code Version**:

1.51.1

**Log Analyzer Extension Version**:

1.3.3

**OS and version**:

Max OS 10.14.5

**Comment by kjonesffdc** [comment]
Thanks for raising this issue. The problem here appears to be that the log file is located outside of the directory that is open in VSCode. I will work on a fix today and hopefully we can get resolved.

**Comment by Dan-Baba** [comment]
Appears to still be an issue even after latest release on Windows, only thing that's changed is 'fsPath' instead of 'path'.

I'm getting the error even if I have the folder open where the log is located too.

**Comment by kjonesffdc** [comment]
Thanks for extra info. The path->fsPath change was for another reason but that certainly helps with locating this. One of our developers saw this just after we had done the initial release. We worked around that by just moving the log file but there may be more to the issue than I understand.

**Comment by jclark-dot-org** [comment]
Confirmed, 1.3.5 is working perfectly for me now.  Thanks!
