### ISSUE TITLE
Add ability to zoom into flame graph

### ISSUE THREAD

**Issue by sjurgis** [financialforcedev/debug-log-analyzer#33]
### Is your feature request related to a problem?
Disabling Shrink to fit helps slightly, but still nearly impossible to drill down into smaller methods (see screenshot).

### Describe the solution you'd like
cmd+scroll to zoom or however it works in chrome dev tools

### Describe alternatives you've considered
Slowly move mouse over peaks, but it's super hard

### Additional context
<img width="2160" alt="Screen Shot 2021-07-20 at 10 31 42 AM" src="https://user-images.githubusercontent.com/7092409/126235845-e9c00fa2-3c16-4eef-ac45-66c5294b82dd.png">

**Comment by kjonesffdc** [comment]
+1

One idea we have seen for this is to support clicking on the flame graph to zoom. The zoom would make the item you clicked the full width of the window so you can repeat the process with any methods it calls. The thought here is that given the range of method sizes it would enable you to get to a good zoom level with a few well placed clicks.

Not against adding other means to zoom as well but of the ways we have looked at, this one we thought was probably the easiest?

**Comment by sjurgis** [comment]
Sounds like a good idea. The problem is how you switch between different peaks or go back to previous one.

I guess it could compliment what's most intuitive - cmd + (-/+) and cmd + scroll up / down, then scroll around like you normally do thru websites (two fingers). I'm a trackpad user so not sure what's the best experience for mouse user.
