### ISSUE TITLE
Doesn't work through command palette or context-menu on downloaded log. Windows?

### ISSUE THREAD

**Issue by dcstuff** [financialforcedev/debug-log-analyzer#4]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

The top error is from right-clicking a log I pulled down and running the command via the context menu.
The bottom error is running the command from the command palette.
Is this a Windows issue? Was the extension tested on Windows? Thanks!
![image](https://user-images.githubusercontent.com/44416270/101833247-acceab00-3b06-11eb-9057-3e986e7af48b.png)

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:
Latest. 1.51.1

**Log Analyzer Extension Version**:
1.3.3

**OS and version**:
Windows 10 latest

**Comment by nicholasglesmann** [comment]
I'm seeing the same issue when right-clicking a log I downloaded.

![image](https://user-images.githubusercontent.com/48044618/101833693-3756e080-3aee-11eb-9450-3959a5f73c98.png)

VS Code Version:
Latest. 1.51.1

Log Analyzer Extension Version:
1.3.3

OS and version:
Windows 10 latest

**Comment by diegonspion** [comment]
Following... same issue...

Downloaded a log, right-click "Log: Show log analysis" and I get the error.
![image](https://user-images.githubusercontent.com/13025579/101834889-0aa6d580-3b8f-11eb-839a-fdd4d4f4f707.png)

![image](https://user-images.githubusercontent.com/13025579/101834989-3629c000-3b8f-11eb-80dc-9b3c5f27bfbb.png)

**Comment by kjonesffdc** [comment]
Thanks for raising the issue. I am not really too sure what is happening here but will do some investigating today.
