### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/c:/Users/anesingh/Desktop/ProjectName/DEV/CSDEV/Apex.log'

### ISSUE THREAD

**Issue by singhaneesh02** [financialforcedev/debug-log-analyzer#5]
Getting this Error when right clicked on log and selected Show log Analysis

Machine OS : - Windows 10
Vs code version :- Recent

**Comment by kjonesffdc** [comment]
Duplicate of #4

**Comment by kjonesffdc** [comment]
This has been fixed in 1.3.4 so I will close.
