### ISSUE TITLE
Command 'Log: Show Log Analysis' resulted in an error (command 'lana.showLogFile' not found)

### ISSUE THREAD

**Issue by Vishalashah** [financialforcedev/debug-log-analyzer#7]
### Summary
Command 'Log: Show Log Analysis' resulted in an error (command 'lana.showLogFile' not found)

### Steps To Reproduce:

1.  Open a log file
2. Run command: Show Log Analysis

### Expected result

Be able to see the log analysis

### Actual result
Command 'Log: Show Log Analysis' resulted in an error (command 'lana.showLogFile' not found)

### Additional information

<img width="260" alt="image" src="https://user-images.githubusercontent.com/365521/101910944-ac2d2780-3b8d-11eb-9142-e6517484512b.png">

VS Code Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Extension version 1.3.4

**OS and version**: macOS Big Sur 11.0.1

**Comment by muralithe1** [comment]
Same Issue. Could somebody help please..

**Comment by nawforce** [comment]
Not really sure what might be cause of this. There is nothing unusual about the environment, almost identical to my dev env. Could you try a couple of things to try narrow down:

1. From the VSCode Help menu select 'Toggle Developer Tools' and check the console for any trace of an exception.
2. If no exception shows, de-install & re-install the extension and try again as the errors looks like the install was only partly successful.

**Comment by nawforce** [comment]
Think I have found source of this, it's related to #8. Will fix but will need to wait until Monday to re-release.
